export const IPC_CHANNELS = {
  shellGetState: "shell:get-state",
  shellStateChanged: "shell:state-changed",
  gatewayListModels: "gateway:list-models",
  gatewayListModelLibrary: "gateway:list-model-library",
  gatewayGetHealth: "gateway:get-health",
  gatewayListEngines: "gateway:list-engines",
  gatewayRegisterLocalModel: "gateway:register-local-model",
  gatewayPreloadModel: "gateway:preload-model",
  gatewayEvictModel: "gateway:evict-model",
  gatewayListChatSessions: "gateway:list-chat-sessions",
  gatewayListChatMessages: "gateway:list-chat-messages",
  gatewayUpsertChatSession: "gateway:upsert-chat-session",
  gatewayRunChat: "gateway:run-chat",
  gatewayListApiLogs: "gateway:list-api-logs",
  gatewaySearchCatalog: "gateway:search-catalog",
  gatewayGetCatalogModel: "gateway:get-catalog-model",
  gatewayListDownloads: "gateway:list-downloads",
  gatewayCreateDownload: "gateway:create-download",
  gatewayPauseDownload: "gateway:pause-download",
  gatewayResumeDownload: "gateway:resume-download",
  gatewayEvent: "gateway:event",
  gatewayOpenModelDialog: "gateway:open-model-dialog",
  systemGetPaths: "system:get-paths",
} as const;
